# Generated by Django 4.1.3 on 2022-12-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_message_text_alter_message_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='count',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
    ]
