# Generated by Django 4.1.3 on 2022-12-17 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2p', '0004_neworder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='change',
            field=models.BooleanField(default=False, verbose_name='возможность редактирования'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
