# Generated by Django 4.1.3 on 2022-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_neworder_change_alter_message_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='payed',
            field=models.BooleanField(default=True, verbose_name='Факт оплаты'),
        ),
    ]
