# Generated by Django 4.1.3 on 2022-12-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0006_alter_neworder_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='change',
            field=models.BooleanField(default=True, verbose_name='Возможность редактирования'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Факт оплаты'),
        ),
    ]
