# Generated by Django 4.1.3 on 2022-12-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0007_alter_neworder_change_alter_neworder_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=0, verbose_name='Количество'),
        ),
    ]
