# Generated by Django 4.1.7 on 2023-04-30 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('changeable', models.BooleanField(default=True, verbose_name='Изменямость')),
            ],
        ),
        migrations.CreateModel(
            name='NftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=4, verbose_name='Валюта')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nft.collection', verbose_name='Коллекция')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='NftPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=4, verbose_name='Валюта')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nftimage', verbose_name='Изображение')),
            ],
        ),
    ]
