# Generated by Django 4.1.7 on 2023-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_alter_nftimage_currency_alter_nftpost_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftimage',
            name='img',
            field=models.ImageField(upload_to='NFTs', verbose_name='Изображение'),
        ),
    ]
