# Generated by Django 4.1.3 on 2022-12-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
