# Generated by Django 4.1.3 on 2022-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
    ]
