# Generated by Django 4.1.3 on 2022-12-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BTC_reserved_payed',
            field=models.IntegerField(default=0, verbose_name='BTC оплаченный резерв'),
        ),
        migrations.AddField(
            model_name='user',
            name='ETH_reserved_payed',
            field=models.IntegerField(default=0, verbose_name='ETH оплаченный резерв'),
        ),
        migrations.AddField(
            model_name='user',
            name='KPFU_reserved_payed',
            field=models.IntegerField(default=0, verbose_name='KPFU оплаченный резерв'),
        ),
        migrations.AddField(
            model_name='user',
            name='SOL_reserved_payed',
            field=models.IntegerField(default=0, verbose_name='SOL оплаченный резерв'),
        ),
        migrations.AddField(
            model_name='user',
            name='USDT_reserved_payed',
            field=models.IntegerField(default=0, verbose_name='USDT оплаченный резерв'),
        ),
    ]
